### ISSUE TITLE
Ansible Integration

### ISSUE THREAD

**Issue by djarbz** [Weilbyte/PVEDiscordDark#38]
I made it work for now, but I don't know if there will be issues down the road based on any changes you make.
It would be nice if you could create an Ansbile Role to automatically download the latest, or specified, version and install/upgrade the theme.

A bonus if you could tag releases so we can refer to specific versions when deploying to multiple servers.

This is what I have so far.

```
  - name: Create a /opt/DiscordDark/ directory if it does not exist
    file:
      path: /opt/DiscordDark/
      state: directory
      mode: '0755'
  
  - name: download PVEDiscordDark
    get_url:
      url: https://raw.githubusercontent.com/Weilbyte/PVEDiscordDark/master/PVEDiscordDark.py
      dest: /opt/DiscordDark/PVEDiscordDark.py
      mode: '0770'
    register: theme_updated

  - name: Check if theme is installed
    stat:
      path: /usr/share/pve-manager/css/dd_style.css
    register: theme_installed

  - name: uninstall old theme
    command: python3 /opt/DiscordDark/PVEDiscordDark.py -a uninstall
    when: theme_updated.changed and theme_installed.stat.exists

  - name: install new theme
    command: python3 /opt/DiscordDark/PVEDiscordDark.py -a install
    when: theme_updated.changed or theme_installed.stat.exists == False
```
